import 'package:mega_empires_assistant/data/advance.dart';
import 'package:mega_empires_assistant/data/advance_colour.dart';
import 'package:mega_empires_assistant/generated/l10n.dart';

enum AdvanceKey {
  mythology,
  deism,
  fundamentalism,
  universalDoctrine,
  enlightenment,
  monotheism,
  theology,
  diaspora,
  empiricism,
  astronavigation,
  coinage,
  medicine,
  cartography,
  calendar,
  library,
  anatomy,
  urbanism,
  monarchy,
  law,
  navalWarfare,
  military,
  democracy,
  publicWorks,
  advancedMilitary,
  provincialEmpire,
  music,
  rhetoric,
  architecture,
  diplomacy,
  politics,
  culturalAscendancy,
  sculpture,
  dramaAndPoetry,
  clothMaking,
  masonry,
  pottery,
  metalWorking,
  agriculture,
  tradeRoutes,
  roadBuilding,
  mining,
  tradeEmpire,
  mysticism,
  writtenRecord,
  theocracy,
  literacy,
  engineering,
  monument,
  philosophy,
  mathematics,
  wonderOfTheWorld,
}

/// All advances available in the game.
final allAdvances = {
  Advance(
      colour1: AdvanceColour.yellow,
      price: 60,
      key: AdvanceKey.mythology,
      title: S.current.advanceNameMythology,
      points: 1,
      discounts: {AdvanceColour.blue: 5, AdvanceColour.yellow: 10},
      specificDiscount: SpecificDiscount(AdvanceKey.literacy, 10)),
  Advance(
      colour1: AdvanceColour.yellow,
      price: 70,
      key: AdvanceKey.deism,
      title: S.current.advanceNameDeism,
      points: 1,
      discounts: {AdvanceColour.yellow: 10, AdvanceColour.orange: 5},
      specificDiscount: SpecificDiscount(AdvanceKey.fundamentalism, 10)),
  Advance(
      colour1: AdvanceColour.yellow,
      price: 150,
      key: AdvanceKey.fundamentalism,
      title: S.current.advanceNameFundamentalism,
      notes: [S.current.advanceNoteFundamentalism],
      points: 3,
      discounts: {AdvanceColour.blue: 5, AdvanceColour.yellow: 10},
      specificDiscount: SpecificDiscount(AdvanceKey.monotheism, 20)),
  Advance(
      colour1: AdvanceColour.yellow,
      price: 160,
      key: AdvanceKey.universalDoctrine,
      title: S.current.advanceNameUniversalDoctrine,
      specialAbilities: [S.current.advanceSpecialAbilityUniversalDoctrine],
      notes: [S.current.advanceNoteUniversalDoctrine],
      points: 3,
      discounts: {AdvanceColour.yellow: 10, AdvanceColour.red: 5},
      specificDiscount: SpecificDiscount(AdvanceKey.theology, 20)),
  Advance(
      colour1: AdvanceColour.yellow,
      price: 160,
      key: AdvanceKey.enlightenment,
      title: S.current.advanceNameEnlightenment,
      points: 3,
      discounts: {AdvanceColour.yellow: 10, AdvanceColour.orange: 5},
      specificDiscount: SpecificDiscount(AdvanceKey.philosophy, 20)),
  Advance(
      colour1: AdvanceColour.yellow,
      price: 240,
      key: AdvanceKey.monotheism,
      title: S.current.advanceNameMonotheism,
      specialAbilities: [S.current.advanceSpecialAbilitiesMonotheism],
      notes: [
        S.current.advanceNotesMonotheism1,
        S.current.advanceNotesMonotheism2
      ],
      points: 6,
      discounts: {AdvanceColour.yellow: 20, AdvanceColour.red: 5}),
  Advance(
      colour1: AdvanceColour.yellow,
      price: 250,
      key: AdvanceKey.theology,
      title: S.current.advanceNameTheology,
      description: S.current.advanceDescriptionTheology,
      points: 6,
      discounts: {AdvanceColour.yellow: 20, AdvanceColour.green: 5}),
  Advance(
      colour1: AdvanceColour.yellow,
      price: 270,
      key: AdvanceKey.diaspora,
      title: S.current.advanceNameDiaspora,
      specialAbilities: [S.current.advanceSpecialAbilitiesDiaspora],
      notes: [S.current.advanceNotesDiaspora1, S.current.advanceNotesDiaspora2],
      points: 6,
      discounts: {AdvanceColour.blue: 5, AdvanceColour.yellow: 20}),
  Advance(
      colour1: AdvanceColour.green,
      price: 60,
      key: AdvanceKey.empiricism,
      title: S.current.advanceNameEmpiricism,
      points: 1,
      discounts: {
        AdvanceColour.blue: 5,
        AdvanceColour.yellow: 5,
        AdvanceColour.orange: 5,
        AdvanceColour.red: 5,
        AdvanceColour.green: 10
      },
      specificDiscount: SpecificDiscount(AdvanceKey.medicine, 10)),
  Advance(
      colour1: AdvanceColour.green,
      price: 80,
      key: AdvanceKey.astronavigation,
      title: S.current.advanceNameAstronavigation,
      description: S.current.advanceDescriptionAstronavigation,
      notes: [S.current.advanceNotesAstronavigation],
      points: 1,
      discounts: {AdvanceColour.yellow: 5, AdvanceColour.green: 10},
      specificDiscount: SpecificDiscount(AdvanceKey.calendar, 10)),
  Advance(
      colour1: AdvanceColour.green,
      price: 90,
      key: AdvanceKey.coinage,
      title: S.current.advanceNameCoinage,
      description: S.current.advanceDescriptionCoinage,
      notes: [
        S.current.advanceNotesCoinage1,
        S.current.advanceNotesCoinage2,
        S.current.advanceNotesCoinage3
      ],
      points: 1,
      discounts: {AdvanceColour.red: 5, AdvanceColour.green: 10},
      specificDiscount: SpecificDiscount(AdvanceKey.tradeRoutes, 10)),
  Advance(
      colour1: AdvanceColour.green,
      price: 140,
      key: AdvanceKey.medicine,
      title: S.current.advanceNameMedicine,
      points: 3,
      discounts: {AdvanceColour.orange: 5, AdvanceColour.green: 10},
      specificDiscount: SpecificDiscount(AdvanceKey.anatomy, 20)),
  Advance(
      colour1: AdvanceColour.green,
      price: 160,
      key: AdvanceKey.cartography,
      title: S.current.advanceNameCartography,
      description: S.current.advanceDescriptionCartography,
      points: 3,
      discounts: {AdvanceColour.blue: 5, AdvanceColour.green: 10},
      specificDiscount: SpecificDiscount(AdvanceKey.library, 20)),
  Advance(
      colour1: AdvanceColour.green,
      price: 180,
      key: AdvanceKey.calendar,
      title: S.current.advanceNameCalendar,
      notes: [S.current.advanceNotesCalendar],
      points: 3,
      discounts: {AdvanceColour.red: 5, AdvanceColour.green: 10},
      specificDiscount: SpecificDiscount(AdvanceKey.publicWorks, 20)),
  Advance(
      colour1: AdvanceColour.green,
      price: 220,
      key: AdvanceKey.library,
      title: S.current.advanceNameLibrary,
      description: S.current.advanceDescriptionLibrary,
      points: 6,
      discounts: {AdvanceColour.blue: 5, AdvanceColour.green: 20}),
  Advance(
      colour1: AdvanceColour.green,
      price: 270,
      key: AdvanceKey.anatomy,
      title: S.current.advanceNameAnatomy,
      description: S.current.advanceDescriptionAnatomy,
      points: 6,
      discounts: {AdvanceColour.orange: 5, AdvanceColour.green: 20}),
  Advance(
      colour1: AdvanceColour.red,
      price: 50,
      key: AdvanceKey.urbanism,
      title: S.current.advanceNameUrbanism,
      description: S.current.advanceDescriptionUrbanism,
      notes: [S.current.advanceNotesUrbanism],
      points: 1,
      discounts: {AdvanceColour.red: 10, AdvanceColour.green: 5},
      specificDiscount: SpecificDiscount(AdvanceKey.diplomacy, 10)),
  Advance(
      colour1: AdvanceColour.red,
      price: 60,
      key: AdvanceKey.monarchy,
      title: S.current.advanceNameMonarchy,
      description: S.current.advanceDescriptionMonarchy,
      notes: [
        S.current.advanceNotesMonarchy1,
        S.current.advanceNotesMonarchy2,
        S.current.advanceNotesMonarchy3
      ],
      points: 1,
      discounts: {AdvanceColour.yellow: 5, AdvanceColour.red: 10},
      specificDiscount: SpecificDiscount(AdvanceKey.law, 10)),
  Advance(
      colour1: AdvanceColour.red,
      price: 150,
      key: AdvanceKey.law,
      title: S.current.advanceNameLaw,
      points: 3,
      discounts: {AdvanceColour.yellow: 5, AdvanceColour.red: 10},
      specificDiscount: SpecificDiscount(AdvanceKey.culturalAscendancy, 20)),
  Advance(
      colour1: AdvanceColour.red,
      price: 160,
      key: AdvanceKey.navalWarfare,
      title: S.current.advanceNameNavalWarfare,
      description: S.current.advanceDescriptionNavalWarfare,
      notes: [
        S.current.advanceNotesNavalWarfare1,
        S.current.advanceNotesNavalWarfare2,
        S.current.advanceNotesNavalWarfare3,
        S.current.advanceNotesNavalWarfare4,
        S.current.advanceNotesNavalWarfare5,
        S.current.advanceNotesNavalWarfare6
      ],
      points: 3,
      discounts: {AdvanceColour.orange: 5, AdvanceColour.red: 10},
      specificDiscount: SpecificDiscount(AdvanceKey.diaspora, 20)),
  Advance(
      colour1: AdvanceColour.red,
      price: 170,
      key: AdvanceKey.military,
      title: S.current.advanceNameMilitary,
      description: S.current.advanceDescriptionMilitary,
      notes: [S.current.advanceNotesMilitary],
      points: 3,
      discounts: {AdvanceColour.orange: 5, AdvanceColour.red: 10},
      specificDiscount: SpecificDiscount(AdvanceKey.advancedMilitary, 20)),
  Advance(
      colour1: AdvanceColour.red,
      price: 220,
      key: AdvanceKey.democracy,
      title: S.current.advanceNameDemocracy,
      description: S.current.advanceDescriptionDemocracy,
      notes: [S.current.advanceNotesDemocracy],
      points: 6,
      discounts: {AdvanceColour.blue: 5, AdvanceColour.red: 20}),
  Advance(
      colour1: AdvanceColour.red,
      price: 230,
      key: AdvanceKey.publicWorks,
      title: S.current.advanceNamePublicWorks,
      description: S.current.advanceDescriptionPublicWorks,
      notes: [
        S.current.advanceNotesPublicWorks1,
        S.current.advanceNotesPublicWorks2,
        S.current.advanceNotesPublicWorks3,
        S.current.advanceNotesPublicWorks4,
        S.current.advanceNotesPublicWorks5,
        S.current.advanceNotesPublicWorks6
      ],
      points: 6,
      discounts: {AdvanceColour.orange: 5, AdvanceColour.red: 20}),
  Advance(
      colour1: AdvanceColour.red,
      price: 240,
      key: AdvanceKey.advancedMilitary,
      title: S.current.advanceNameAdvancedMilitary,
      description: S.current.advanceDescriptionAdvancedMilitary,
      notes: [
        S.current.advanceNotesAdvancedMilitary1,
        S.current.advanceNotesAdvancedMilitary2,
        S.current.advanceNotesAdvancedMilitary3,
        S.current.advanceNotesAdvancedMilitary4
      ],
      points: 6,
      discounts: {AdvanceColour.red: 20, AdvanceColour.green: 5}),
  Advance(
      colour1: AdvanceColour.red,
      price: 260,
      key: AdvanceKey.provincialEmpire,
      title: S.current.advanceNameProvincialEmpire,
      specialAbilities: [S.current.advanceSpecialAbilitiesProvincialEmpire],
      notes: [S.current.advanceNotesProvincialEmpire],
      points: 6,
      discounts: {AdvanceColour.yellow: 5, AdvanceColour.red: 20}),
  Advance(
      colour1: AdvanceColour.blue,
      price: 80,
      key: AdvanceKey.music,
      title: S.current.advanceNameMusic,
      points: 1,
      discounts: {AdvanceColour.blue: 10, AdvanceColour.yellow: 5},
      specificDiscount: SpecificDiscount(AdvanceKey.enlightenment, 10)),
  Advance(
      colour1: AdvanceColour.blue,
      price: 130,
      key: AdvanceKey.rhetoric,
      title: S.current.advanceNameRhetoric,
      description: S.current.advanceDescriptionRhetoric,
      points: 3,
      discounts: {AdvanceColour.blue: 10, AdvanceColour.red: 5},
      specificDiscount: SpecificDiscount(AdvanceKey.politics, 20)),
  Advance(
      colour1: AdvanceColour.blue,
      price: 140,
      key: AdvanceKey.architecture,
      title: S.current.advanceNameArchitecture,
      description: S.current.advanceDescriptionArchitecture,
      notes: [S.current.advanceNotesArchitecture],
      points: 3,
      discounts: {AdvanceColour.blue: 10, AdvanceColour.green: 5},
      specificDiscount: SpecificDiscount(AdvanceKey.mining, 20)),
  Advance(
      colour1: AdvanceColour.blue,
      price: 160,
      key: AdvanceKey.diplomacy,
      title: S.current.advanceNameDiplomacy,
      description: S.current.advanceDescriptionDiplomacy,
      notes: [
        S.current.advanceNotesDiplomacy1,
        S.current.advanceNotesDiplomacy2,
        S.current.advanceNotesDiplomacy3
      ],
      points: 3,
      discounts: {AdvanceColour.blue: 10, AdvanceColour.red: 5},
      specificDiscount: SpecificDiscount(AdvanceKey.provincialEmpire, 20)),
  Advance(
      colour1: AdvanceColour.blue,
      price: 230,
      key: AdvanceKey.politics,
      title: S.current.advanceNamePolitics,
      specialAbilities: [S.current.advanceSpecialAbilitiesPolitics],
      notes: [
        S.current.advanceNotesPolitics1,
        S.current.advanceNotesPolitics2,
        S.current.advanceNotesPolitics3
      ],
      points: 6,
      discounts: {AdvanceColour.blue: 20, AdvanceColour.yellow: 5}),
  Advance(
      colour1: AdvanceColour.blue,
      price: 280,
      key: AdvanceKey.culturalAscendancy,
      title: S.current.advanceNameCulturalAscendancy,
      description: S.current.advanceDescriptionCulturalAscendancy,
      notes: [
        S.current.advanceNotesCulturalAscendancy1,
        S.current.advanceNotesCulturalAscendancy2,
        S.current.advanceNotesCulturalAscendancy3,
        S.current.advanceNotesCulturalAscendancy4,
        S.current.advanceNotesCulturalAscendancy5,
        S.current.advanceNotesCulturalAscendancy6
      ],
      points: 6,
      discounts: {AdvanceColour.blue: 20, AdvanceColour.yellow: 5}),
  Advance(
      colour1: AdvanceColour.blue,
      price: 50,
      key: AdvanceKey.sculpture,
      title: S.current.advanceNameSculpture,
      points: 1,
      discounts: {AdvanceColour.blue: 10, AdvanceColour.red: 5},
      specificDiscount: SpecificDiscount(AdvanceKey.architecture, 10)),
  Advance(
      colour1: AdvanceColour.blue,
      price: 80,
      key: AdvanceKey.dramaAndPoetry,
      title: S.current.advanceNameDramaAndPoetry,
      points: 1,
      discounts: {AdvanceColour.blue: 10, AdvanceColour.yellow: 5},
      specificDiscount: SpecificDiscount(AdvanceKey.rhetoric, 10)),
  Advance(
      colour1: AdvanceColour.orange,
      price: 50,
      key: AdvanceKey.clothMaking,
      title: S.current.advanceNameClothMaking,
      description: S.current.advanceDescriptionClothMaking,
      points: 1,
      discounts: {AdvanceColour.blue: 5, AdvanceColour.orange: 10},
      specificDiscount: SpecificDiscount(AdvanceKey.navalWarfare, 10)),
  Advance(
      colour1: AdvanceColour.orange,
      price: 60,
      key: AdvanceKey.masonry,
      title: S.current.advanceNameMasonry,
      notes: [S.current.advanceNotesMasonry],
      points: 1,
      discounts: {AdvanceColour.orange: 10, AdvanceColour.green: 5},
      specificDiscount: SpecificDiscount(AdvanceKey.engineering, 10)),
  Advance(
      colour1: AdvanceColour.orange,
      price: 60,
      key: AdvanceKey.pottery,
      title: S.current.advanceNamePottery,
      points: 1,
      discounts: {AdvanceColour.blue: 5, AdvanceColour.orange: 10},
      specificDiscount: SpecificDiscount(AdvanceKey.agriculture, 10)),
  Advance(
      colour1: AdvanceColour.orange,
      price: 90,
      key: AdvanceKey.metalWorking,
      title: S.current.advanceNameMetalworking,
      description: S.current.advanceDescriptionMetalworking,
      notes: [S.current.advanceNotesMetalworking],
      points: 1,
      discounts: {AdvanceColour.orange: 10, AdvanceColour.red: 5},
      specificDiscount: SpecificDiscount(AdvanceKey.military, 10)),
  Advance(
      colour1: AdvanceColour.orange,
      price: 120,
      key: AdvanceKey.agriculture,
      title: S.current.advanceNameAgriculture,
      description: S.current.advanceDescriptionAgriculture,
      notes: [
        S.current.advanceNotesAgriculture1,
        S.current.advanceNotesAgriculture2,
        S.current.advanceNotesAgriculture3,
        S.current.advanceNotesAgriculture4
      ],
      points: 3,
      discounts: {AdvanceColour.orange: 10, AdvanceColour.green: 5},
      specificDiscount: SpecificDiscount(AdvanceKey.democracy, 20)),
  Advance(
      colour1: AdvanceColour.orange,
      price: 180,
      key: AdvanceKey.tradeRoutes,
      title: S.current.advanceNameTradeRoutes,
      specialAbilities: [S.current.advanceSpecialAbilitiesTradeRoutes],
      notes: [S.current.advanceNotesTradeRoutes],
      points: 3,
      discounts: {AdvanceColour.yellow: 5, AdvanceColour.orange: 10},
      specificDiscount: SpecificDiscount(AdvanceKey.tradeEmpire, 20)),
  Advance(
      colour1: AdvanceColour.orange,
      price: 220,
      key: AdvanceKey.roadBuilding,
      title: S.current.advanceNameRoadbuilding,
      description: S.current.advanceDescriptionRoadbuilding,
      notes: [
        S.current.advanceNotesRoadbuilding1,
        S.current.advanceNotesRoadbuilding2
      ],
      points: 6,
      discounts: {AdvanceColour.orange: 20, AdvanceColour.green: 5},
      handLimitModifier: 1),
  Advance(
      colour1: AdvanceColour.orange,
      price: 230,
      key: AdvanceKey.mining,
      title: S.current.advanceNameMining,
      description: S.current.advanceDescriptionMining,
      notes: [
        // TODO: This isn't enforced in the app
        S.current.advanceNotesMining
      ],
      points: 6,
      discounts: {AdvanceColour.orange: 20, AdvanceColour.green: 5}),
  Advance(
      colour1: AdvanceColour.orange,
      price: 260,
      key: AdvanceKey.tradeEmpire,
      title: S.current.advanceNameTradeEmpire,
      description: S.current.advanceDescriptionTradeEmpire,
      points: 6,
      discounts: {AdvanceColour.orange: 20, AdvanceColour.red: 5}),
  Advance(
      colour1: AdvanceColour.blue,
      colour2: AdvanceColour.yellow,
      price: 50,
      key: AdvanceKey.mysticism,
      title: S.current.advanceNameMysticism,
      points: 1,
      discounts: {AdvanceColour.blue: 5, AdvanceColour.yellow: 5},
      specificDiscount: SpecificDiscount(AdvanceKey.monument, 10)),
  Advance(
      colour1: AdvanceColour.red,
      colour2: AdvanceColour.green,
      price: 60,
      key: AdvanceKey.writtenRecord,
      title: S.current.advanceNameWrittenRecord,
      description: S.current.advanceDescriptionWrittenRecord,
      notes: [S.current.advanceNotesWrittenRecord],
      points: 1,
      discounts: {AdvanceColour.red: 5, AdvanceColour.green: 5},
      specificDiscount: SpecificDiscount(AdvanceKey.cartography, 10),
      optionalCredits: 10),
  Advance(
      colour1: AdvanceColour.red,
      colour2: AdvanceColour.yellow,
      price: 80,
      key: AdvanceKey.theocracy,
      title: S.current.advanceNameTheocracy,
      notes: [
        S.current.advanceNotesTheocracy1,
        S.current.advanceNotesTheocracy2
      ],
      points: 1,
      discounts: {AdvanceColour.yellow: 5, AdvanceColour.red: 5},
      specificDiscount: SpecificDiscount(AdvanceKey.universalDoctrine, 10)),
  Advance(
      colour1: AdvanceColour.blue,
      colour2: AdvanceColour.red,
      price: 110,
      key: AdvanceKey.literacy,
      title: S.current.advanceNameLiteracy,
      points: 3,
      discounts: {
        AdvanceColour.blue: 10,
        AdvanceColour.yellow: 5,
        AdvanceColour.orange: 5,
        AdvanceColour.red: 10,
        AdvanceColour.green: 5
      },
      specificDiscount: SpecificDiscount(AdvanceKey.mathematics, 20)),
  Advance(
      colour1: AdvanceColour.orange,
      colour2: AdvanceColour.green,
      price: 160,
      key: AdvanceKey.engineering,
      title: S.current.advanceNameEngineering,
      description: S.current.advanceDescriptionEngineering,
      points: 3,
      discounts: {AdvanceColour.orange: 10, AdvanceColour.green: 10},
      specificDiscount: SpecificDiscount(AdvanceKey.roadBuilding, 20)),
  Advance(
      colour1: AdvanceColour.orange,
      colour2: AdvanceColour.yellow,
      price: 180,
      key: AdvanceKey.monument,
      title: S.current.advanceNameMonument,
      description: S.current.advanceDescriptionMonument,
      notes: [S.current.advanceNotesMonument],
      points: 3,
      discounts: {AdvanceColour.yellow: 10, AdvanceColour.orange: 10},
      specificDiscount: SpecificDiscount(AdvanceKey.wonderOfTheWorld, 20),
      optionalCredits: 20),
  Advance(
      colour1: AdvanceColour.yellow,
      colour2: AdvanceColour.green,
      price: 220,
      key: AdvanceKey.philosophy,
      title: S.current.advanceNamePhilosophy,
      description: S.current.advanceDescriptionPhilosophy,
      points: 6,
      discounts: {AdvanceColour.yellow: 20, AdvanceColour.green: 20}),
  Advance(
      colour1: AdvanceColour.blue,
      colour2: AdvanceColour.green,
      price: 250,
      key: AdvanceKey.mathematics,
      title: S.current.advanceNameMathematics,
      points: 6,
      discounts: {
        AdvanceColour.blue: 20,
        AdvanceColour.yellow: 10,
        AdvanceColour.orange: 10,
        AdvanceColour.red: 10,
        AdvanceColour.green: 20
      }),
  Advance(
      colour1: AdvanceColour.blue,
      colour2: AdvanceColour.orange,
      price: 290,
      key: AdvanceKey.wonderOfTheWorld,
      title: S.current.advanceNameWonderOfTheWorld,
      description: S.current.advanceDescriptionWonderOfTheWorld,
      notes: [
        S.current.advanceNotesWonderOfTheWorld1,
        S.current.advanceNotesWonderOfTheWorld2
      ],
      points: 6,
      discounts: {AdvanceColour.blue: 20, AdvanceColour.orange: 20}),
};

/// ALL_ADVANCES indexed by advance title.
final indexedAdvances = {for (var e in allAdvances) e.key: e};
